### ISSUE TITLE
so like wheres the exe file?

### ISSUE THREAD

**Issue by ascdragonite** [IVogel/tModUnpacker#2]
or do i need to do something else

**Comment by IVogel** [comment]
You should download [this](https://github.com/IVogel/tModUnpacker/releases/download/1.2/tModUnpacker.7z).
If you don't have 7-zip, then you have to download [this](https://www.7-zip.org/). (Or anything else that can open 7z archives)

**Comment by 3ICE** [comment]
Ah! That'd've been so much easier...

I downloaded Visual Studio 2013, retargeted the project to .NET Framework 4.5, created the missing AssemblyInfo file:
```
Error	1	Source file 'Properties\AssemblyInfo.cs' could not be found
C:\Users\3ICE\Downloads\tModUnpacker-master\tModUnpacker\CSC	tModUnpacker
1>CSC : error CS2001: Source file 'Properties\AssemblyInfo.cs' could not be found
```

(Filled it in with bogus information for name, company, copyright, version, language, etc.) — Even used a fake GUID from some random generator:
[assembly: Guid("3f139233-3c89-43d3-303a-367d331723e1")]


Fixed all the code errors by hand:
`Error	1	Unexpected character '$'	tModUnpacker\main.cs	14	5`

And more:
```
Error	1	Unexpected character '$'	main.cs	33	60
Error	2	The best overloaded method match for 'tModUnpacker.tMod.DumpFiles(string, System.Action<string>)' has some invalid arguments	main.cs	33	4
Error	3	Argument 2: cannot convert from 'lambda expression' to 'System.Action<string>'	main.cs	33	30
Error	4	Only assignment, call, increment, decrement, await, and new object expressions can be used as a statement	main.cs	33	61
Error	5	Only assignment, call, increment, decrement, await, and new object expressions can be used as a statement	main.cs	33	84
Error	6	Invalid expression term ''	main.cs	33	60
Error	7	) expected	main.cs	33	61
Error	8	Invalid expression term ')'	main.cs	33	84
Error	9	; expected	main.cs	33	84
Error	10	Invalid expression term ')'	main.cs	33	85
Error	11	; expected	main.cs	33	85
```

And even more upon compiling:
`1>tModUnpacker\main.cs(17,5,17,6): error CS1056: Unexpected character '$'`

Then figured out why the exit on load:
```
'tModUnpacker.vshost.exe' (CLR v4.0.30319: tModUnpacker.vshost.exe): Loaded 'tModUnpacker\bin\Debug\tModUnpacker.vshost.exe'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'tModUnpacker.vshost.exe' (CLR v4.0.30319: tModUnpacker.vshost.exe): Loaded 'tModUnpacker\bin\Debug\tModUnpacker.exe'. Symbols loaded.

The thread 0xa04 has exited with code 259 (0x103).
The program '[5896] tModUnpacker.vshost.exe' has exited with code 0 (0x0).
```

I had to specify command line arguments pre-launch... And might I add; in a very convoluted way! (Through debugging settings, instead of being able to simply type it into the console after .exe)

All this trouble because I didn't see the super useful releases option, only a code download button.

Can you please link to this precompiled download option in the readme.md file? GitHub hides the releases on my screen resolution. It's pushed off-screen. Just [github.com/IVogel/tModUnpacker/releases](https://github.com/IVogel/tModUnpacker/releases/) would be enough of a pointer.

This was quite the adventure!
